### ISSUE TITLE
Reward module on line #920

### ISSUE THREAD

**Issue by rxRibo** [RXbenjoZork/Retrex#3]
`if` (chainActive.Height() % 78 != 2000) return;

Was staring at this for 2 hours now 🗡️  revision needed

**Comment by RXbenjoZork** [comment]
bool std::object on line #1003 is the culprit check it out.

After this test it on "#2 PR"

I can merge it till you can compile it.

**Comment by RXbenjoZork** [comment]
I can close this one now FIXED on line #30 from rxDrinez´s end
